# Generated by Django 3.1.5 on 2021-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcfield',
            name='age',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='calcfield',
            name='height',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='calcfield',
            name='weight',
            field=models.IntegerField(unique=True),
        ),
    ]
